branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

language: cpp
sudo: required

os:
  - linux
#    - osx

compiler:
  - g++
#    - clang

dist: trusty
#osx_image: xcode10

before_install:
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${MATRIX_EVAL}" fi
  - git submodule update --init --recursive

script:
  - mkdir build && cd build && cmake .. && make
  - ctest -VV

notifications:
  email:
    recipients:
      - iuniqums@gmail.com
    on_success: change
    on_failure: always
