branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git
    - BUILD_DIR: build

sudo: required

matrix:
  include:
    - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
- sudo apt-get -qq update
- eval "${MATRIX_EVAL}"
- git submodule update --init --recursive

script:
- mkdir build && cd build && cmake .. && make
- ctest -VV

notifications:
  email:
    recipients:
    - iuniqums@gmail.com
    on_success: change
    on_failure: always
