branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git
    - BUILD_DIR: build

sudo: required
os: linux
dist: trusty
language: cpp
compiler: gcc

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER=g++-6
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.9
        packages:
        - libc++-dev
        - clang-3.9
    env:
    - COMPILER=clang++-3.9
    - COMPILER_FLAGS=-stdlib=libc++

git:
  submodules: false

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y x11proto-input-dev libxmu-dev mesa-common-dev freeglut3-dev libx11-xcb-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
- git submodule update --init --recursive

script:
- mkdir build && cd build && cmake .. && make -j{nproc}
#- ctest -VV

notifications:
  email:
    recipients:
    - iuniqums@gmail.com
    on_success: change
    on_failure: always
