branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git

language: cpp
sudo: required

matrix:
  include:
#  - os: linux
#    dist: trusty
#    compiler: g++
  - os: osx
    compiler: clang


before_install:
  - git submodule update --init --recursive

script:
  - mkdir build && cd build && cmake .. && make
  - ctest -VV

notifications:
  email:
    recipients:
      - iuniqums@gmail.com
    on_success: change
    on_failure: always
