branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git
    - BUILD_DIR: build

language: cpp
sudo: required

os:
  - linux
  - osx

compiler: g++
dist: trusty

before_install:
  - git submodule update --init --recursive

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x travisBuild.sh
  - ./travisBuild.sh

notifications:
  email:
    recipients:
    - iuniqums@gmail.com
    on_success: change
    on_failure: always
