branches:
  except:
    gh-pages

env:
  global:
    - GH_REPO_NAME: Pony
    - GH_REPO_REF: github.com/Godlike/Pony.git

language: cpp
sudo: required

os:
  - linux
  - osx

compiler: g++
dist: trusty

env:
  - MATRIX_EVAL="CC=gcc && CXX=g++"
  - BUILD_DIR="build"

before_install:
  - eval "${MATRIX_EVAL} ${BUILD_DIR}"
  - git submodule update --init --recursive

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x travisBuildScript.sh
  - ./travisBuildScript.sh

notifications:
  email:
    recipients:
      - iuniqums@gmail.com
    on_success: change
    on_failure: always
