version: 1.0.{build}

image: Visual Studio 2017

configuration:
  - Debug
  - Release
platform: x64
clone_folder: "c:\\Pony"

init:
install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: "build\\Pony.sln"
  parallel: true
  verbosity: minimal

test:
  - cd %APPVEYOR_BUILD_FOLDER%/build
  - ctest -VV -C %CONFIGURATION%

notifications:
  - provider: Email
  to: - iuniqums@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
